//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by MultiMonitor.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_MULTIMONITOR_DIALOG         102
#define IDP_SOCKETS_INIT_FAILED         103
#define IDR_MAINFRAME                   128
#define IDD_DIALOG1                     129
#define IDD_DIALOG_MDS                  129
#define IDD_DIALOG_TRANS                130
#define IDB_HEADERCTRL_SPAN_NORMAL      131
#define IDB_BITMAP1                     133
#define IDB_HEADERCTRL_END_NORMAL       133
#define IDD_DIALOG_GRA                  134
#define IDD_DIALOG_TRANSDELAY           135
#define IDR_MENU1                       137
#define IDD_DIALOG_TRANSSERVER          138
#define IDD_DIALOG_TRANS_GQS            139
#define IDD_DIALOG_CALCULATION_SERVER   140
#define IDR_MENU2                       141
#define IDD_DIALOG_SEARCH_TRANS         142
#define IDR_ACCELERATOR1                143
#define IDD_DIALOG_TRANS_DETAILS        144
#define IDR_ACCELERATOR2                145
#define IDR_MENU3                       146
#define IDC_LIST_DATA                   1000
#define IDC_LIST1                       1003
#define IDC_LIST_GRA                    1003
#define IDC_LIST_TRANSSERVER            1003
#define IDC_LIST_TRANSFULL              1003
#define IDC_LIST_CALCULATION_SERVER     1003
#define IDC_TAB1                        1004
#define IDC_LIST2                       1005
#define IDC_LIST_TRANS                  1006
#define IDC_LIST_MDS                    1009
#define IDC_STATIC_SRV                  1016
#define IDC_STATIC_SRV_ERR              1017
#define IDC_STATIC_GRA                  1018
#define IDC_STATIC_SEL1                 1019
#define IDC_EDIT_SEL1                   1021
#define IDC_EDIT_BUY1                   1022
#define IDC_STATIC_BUY1                 1023
#define IDC_STATIC_LATESTP              1024
#define IDC_EDIT_LATESTP                1025
#define IDC_STATIC_VOL                  1026
#define IDC_EDIT_VOL                    1027
#define IDC_EDIT_AMOUNT                 1028
#define IDC_STATIC_AMOUNT               1029
#define IDC_EDIT_HIGH                   1030
#define IDC_STATIC_HIGH                 1031
#define IDC_EDIT_LOW                    1032
#define IDC_STATIC_LOW                  1033
#define IDC_EDIT_OPEN                   1034
#define IDC_STATIC_OPEN                 1035
#define IDC_EDIT_CLOSE                  1036
#define IDC_STATIC_CLOSE                1037
#define IDC_EDIT_INVHOLD                1038
#define IDC_STATIC_INVHOLD              1039
#define IDC_EDIT_PRESET                 1040
#define IDC_STATIC_PRESET               1041
#define IDC_EDIT_DATE                   1042
#define IDC_STATIC_DATE                 1043
#define IDC_EDIT_TIME                   1044
#define IDC_STATIC_TIME                 1045
#define IDC_EDIT_CODE                   1046
#define IDC_STATIC_CODE                 1047
#define IDC_COMBO_SERVER                1049
#define IDC_STATIC_SERVER               1050
#define IDC_STATIC_PORT                 1052
#define IDC_STATIC_Market               1052
#define IDC_COMBO_MARKET                1053
#define IDC_EDIT_SETTLE                 1054
#define IDC_STATIC_SETTLE               1055
#define IDC_EDIT_AVG                    1056
#define IDC_STATIC_AVG                  1057
#define IDC_EDIT_TRDNUM                 1058
#define IDC_STATIC_TRDNUM               1059
#define IDC_EDIT_PREINV                 1060
#define IDC_STATIC_PREINV               1061
#define IDC_EDIT_BUY2                   1062
#define IDC_STATIC_BUY2                 1063
#define IDC_EDIT_BUY3                   1064
#define IDC_EDIT_BUY4                   1065
#define IDC_EDIT_BUY5                   1066
#define IDC_STATIC_BUY3                 1068
#define IDC_STATIC_BUY4                 1069
#define IDC_STATIC_BUY5                 1070
#define IDC_EDIT_SEL2                   1071
#define IDC_EDIT_SEL3                   1072
#define IDC_EDIT_SEL4                   1073
#define IDC_EDIT_SEL5                   1074
#define IDC_STATIC_SEL2                 1075
#define IDC_STATIC_SEL3                 1076
#define IDC_STATIC_SEL4                 1077
#define IDC_STATIC_SEL5                 1078
#define IDCFLASH                        1079
#define IDC_LIST_TRANSDELAY             1084
#define IDC_EDIT_IP                     1088
#define IDC_SPIN_PAGE                   1091
#define IDC_BUTTON_SHOWFULL             1097
#define IDC_EDIT_IP2                    1098
#define IDC_COMBO2                      1100
#define IDC_EDIT1                       1101
#define IDC_LIST_TRANS_GQS              1102
#define IDC_EDIT_REFRESH_TIME3          1103
#define IDC_EDIT_REFRESH_TIME4          1104
#define IDC_EDIT_REFRESH_TIME1          1104
#define IDC_EDIT_REFRESH_TIME5          1105
#define IDC_EDIT_REFRESH_TIME2          1105
#define IDC_EDIT_REFRESH_TIME6          1106
#define IDC_COMBO_SEARCH_TRANS          1107
#define IDC_COMBO_IP_LIST               1109
#define IDC_STATIC_SEARCH               1110
#define IDC_EDIT_IPLIST1                1111
#define IDC_EDIT_IPLIST2                1112
#define IDC_EDIT_IPLIST3                1113
#define IDC_STATIC_IPLIST               1114
#define IDC_STATIC_REFRESHTIME          1115
#define ID_DETAILS_DETAILS              32772
#define ID_MENU_COPY_SERVER_IP          32773
#define ID_DETAILS_COPYUPSTREAMIP       32774
#define ID_MENU_COPY_UPSTREAM_IP        32775
#define ID_EDIT_SEARCH                  32776
#define ID_EDIT_HELP                    32777
#define ID_EDIT_SEARCH_TRANS            32778
#define ID_EDIT_DETAILS                 32781
#define ID_DETAILS_DETAILS32784         32784
#define ID_DETAILS_DETAILSMARKET        32785
#define ID_DETAILS_ENABLEPOPUP          32786
#define ID_DETAILS_DISABLEPOPUP         32787
#define ID_DETAILS_ENABLEPOPUP32788     32788
#define ID_DETAILS_PICKUPACOLOR         32789
#define ID_EDIT_AUTOPOPUP               32790
#define ID_EDIT_PLAYMUSIC               32791

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        147
#define _APS_NEXT_COMMAND_VALUE         32792
#define _APS_NEXT_CONTROL_VALUE         1116
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
